const express = require('express');
const crypto = require('crypto');
const User = require('../models/User');
const Beneficiary = require('../models/Beneficiary');
const Asset = require('../models/Asset');
const Capsule = require('../models/Capsule');
const { sendEmail } = require('../utils/email');

const router = express.Router();

// Generate emergency access code
router.post('/generate-code', async (req, res) => {
  try {
    const { userId, beneficiaryId } = req.body;
    
    // Generate 8-character access code
    const accessCode = crypto.randomBytes(4).toString('hex').toUpperCase();
    const expiresAt = new Date(Date.now() + 24 * 60 * 60 * 1000); // 24 hours
    
    // Update beneficiary with access code
    await Beneficiary.findByIdAndUpdate(beneficiaryId, {
      emergencyAccessCode: accessCode,
      emergencyAccessExpires: expiresAt
    });
    
    res.json({
      success: true,
      data: {
        accessCode,
        expiresAt
      }
    });
  } catch (error) {
    console.error('Generate access code error:', error);
    res.status(500).json({ error: 'Failed to generate access code' });
  }
});

// Verify emergency access
router.post('/access', async (req, res) => {
  try {
    const { code } = req.body;
    
    if (!code || code.length !== 8) {
      return res.status(400).json({
        success: false,
        message: 'Invalid access code format'
      });
    }
    
    // Find beneficiary with valid access code
    const beneficiary = await Beneficiary.findOne({
      emergencyAccessCode: code,
      emergencyAccessExpires: { $gt: new Date() }
    }).populate('userId');
    
    if (!beneficiary) {
      return res.status(400).json({
        success: false,
        message: 'Invalid or expired access code'
      });
    }
    
    // Get user data
    const user = await User.findById(beneficiary.userId._id);
    if (!user) {
      return res.status(404).json({
        success: false,
        message: 'User not found'
      });
    }
    
    // Get assets and capsules for this user
    const [assets, capsules] = await Promise.all([
      Asset.find({ userId: user._id }),
      Capsule.find({ userId: user._id })
    ]);
    
    // Update beneficiary access log
    await Beneficiary.findByIdAndUpdate(beneficiary._id, {
      accessGrantedAt: new Date(),
      lastAccessAt: new Date()
    });
    
    res.json({
      success: true,
      data: {
        user: {
          name: user.name,
          email: user.email,
          triggerStatus: user.triggerStatus
        },
        beneficiary: {
          name: beneficiary.name,
          relationship: beneficiary.relationship,
          email: beneficiary.email,
          accessGrantedAt: beneficiary.accessGrantedAt
        },
        assets: assets,
        capsules: capsules
      }
    });
  } catch (error) {
    console.error('Emergency access error:', error);
    res.status(500).json({ error: 'Failed to verify access' });
  }
});

// Download asset credentials
router.get('/download/:assetId', async (req, res) => {
  try {
    const { assetId } = req.params;
    
    // In a real implementation, you might want to verify access
    // For now, we'll just return the encrypted asset data
    
    const asset = await Asset.findById(assetId);
    if (!asset) {
      return res.status(404).json({ error: 'Asset not found' });
    }
    
    // Create downloadable content
    let content = `${asset.platform} Credentials\n${'='.repeat(30)}\n`;
    content += `Username: ${asset.username}\n`;
    content += `Password: ${asset.password}\n`;
    if (asset.instruction) {
      content += `Instruction: ${asset.instruction}\n`;
    }
    content += `${'='.repeat(30)}\n`;
    content += `Generated by LastKey Emergency Access\n`;
    content += `Date: ${new Date().toISOString()}\n`;
    
    res.setHeader('Content-Type', 'text/plain');
    res.setHeader('Content-Disposition', `attachment; filename="${asset.platform}-credentials.txt"`);
    res.send(content);
  } catch (error) {
    console.error('Download asset error:', error);
    res.status(500).json({ error: 'Failed to download asset' });
  }
});

// Send notification to estate administrator
router.post('/notify', async (req, res) => {
  try {
    const { beneficiaryId, message } = req.body;
    
    const beneficiary = await Beneficiary.findById(beneficiaryId).populate('userId');
    if (!beneficiary) {
      return res.status(404).json({ error: 'Beneficiary not found' });
    }
    
    // Send notification email to estate admin (you might want to configure this)
    const adminEmail = process.env.ESTATE_ADMIN_EMAIL || 'admin@lastkey.com';
    
    await sendEmail({
      to: adminEmail,
      subject: 'Emergency Access Notification',
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
          <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px; border-radius: 10px; text-align: center; color: white;">
            <h1 style="margin: 0; font-size: 32px;">Emergency Access Confirmation</h1>
            <p style="margin: 10px 0 0 0; font-size: 18px;">LastKey Digital Legacy</p>
          </div>
          
          <div style="padding: 30px; background: #f9f9f9; border-radius: 10px; margin: 20px 0;">
            <h2 style="color: #333; margin-bottom: 20px;">Access Details</h2>
            
            <div style="background: #fff; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
              <p><strong>Account Owner:</strong> ${beneficiary.userId.name}</p>
              <p><strong>Beneficiary:</strong> ${beneficiary.name} (${beneficiary.relationship})</p>
              <p><strong>Access Time:</strong> ${new Date().toLocaleString()}</p>
              <p><strong>Message:</strong> ${message}</p>
            </div>
            
            <p style="color: #666; font-size: 14px; text-align: center;">
              This is an automated notification from the LastKey Emergency Access Portal.
            </p>
          </div>
        </div>
      `
    });
    
    res.json({
      success: true,
      message: 'Notification sent successfully'
    });
  } catch (error) {
    console.error('Notify error:', error);
    res.status(500).json({ error: 'Failed to send notification' });
  }
});

module.exports = router;
